<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQjMi1hC\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQjMi1hC/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQjMi1hC.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQjMi1hC\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQjMi1hC\appAppKernelProdContainer([
    'container.build_hash' => 'QjMi1hC',
    'container.build_id' => '64c6837b',
    'container.build_time' => 1702832831,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQjMi1hC');
